language: nix
script: nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/2231575a7ddd768fbce7d8f0c75926e5f1ee5c95.tar.gz --run "runhaskell site.hs build"
after_success: bash .ci/update_pages.sh
