branches:
  only: master
language: python
python: 3.6
cache: pip
script: make html
notifications:
  email:
    on_success: always
    on_failure: always
before_install: git submodule update --init --recursive
after_success: bash deploy.sh
env:
  global:
    secure: Ew3edSrbYr/rofui49TpBTbmHivreifr0FLjqP+1CBPXERKEsCjs9thWBnjKIZYirfetMb5ShF9EZ1g8D459BS7Sn+ziXUP4X3I4jvdx1Yj55o2CuWOD6Gx6ShPkWEhZRZhFFIKpGfLO4XAKP3suSPJvB1Lp67GC0BFyPucSSU8=
